defaults: &defaults
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *defaults
  host: localhost
  encoding: UTF8
  adapter: postgresql
  database: pos_development
  pool: 5
  timeout: 5000

test:
  <<: *defaults
  host: localhost
  encoding: UTF8
  adapter: postgresql
  database: pos_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <% ENV[POS_PRODUCTION_DB] %>
  pool: 5
  timeout: 5000
